# Generated by Django 5.1.6 on 2025-02-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('employment_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employmentapplication')),
            ],
        ),
    ]
