# Generated by Django 5.1.6 on 2025-03-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentapplication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
