# Generated by Django 5.1.6 on 2025-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_applicantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_upload_documents',
            field=models.BooleanField(default=False, help_text='Can user upload documents?'),
        ),
    ]
