# Generated by Django 5.1.6 on 2025-03-07 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_profile_is_active_profile_is_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('safety', 'Safety'), ('equipment', 'Equipment'), ('environmental', 'Environmental'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hazard_photos/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
