# Generated by Django 5.1.6 on 2025-03-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_submissiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='crew',
            field=models.ForeignKey(blank=True, help_text='Assigned crew', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.crew'),
        ),
    ]
