# Generated by Django 5.1.6 on 2025-03-09 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_crew_profile_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cell_number',
            field=models.CharField(blank=True, help_text='Format: +12345678901 or 1234567890', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='employee_pictures/'),
        ),
    ]
