# Generated by Django 5.1.6 on 2025-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_site_remove_profile_crew_crew_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_crew_leader',
            field=models.BooleanField(default=False, help_text='Designates this user as a crew leader'),
        ),
    ]
