# Generated by Django 5.1.6 on 2025-03-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_profile_is_crew_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AR', 'Arkansas'), ('FL', 'Florida'), ('LA', 'Louisiana'), ('MS', 'Mississippi'), ('NC', 'North Carolina'), ('OK', 'Oklahoma'), ('TX', 'Texas'), ('OF', 'Offshore')], max_length=2),
        ),
    ]
