# Generated by Django 5.1.6 on 2025-03-11 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def assign_unique_employee_ids(apps, schema_editor):
    Profile = apps.get_model('hr', 'Profile')
    profiles = Profile.objects.filter(employee_id='')
    for i, profile in enumerate(profiles, start=1):
        # Assign a temporary unique ID, e.g., "TEMP-0001"
        profile.employee_id = f"TEMP-{str(i).zfill(4)}"
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_employmentapplication_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entry', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tkt_no', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('job_id', models.CharField(blank=True, max_length=20)),
                ('job_no', models.CharField(blank=True, max_length=20)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('emp_id', models.CharField(blank=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('pr_date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perdiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entry', models.CharField(blank=True, max_length=2)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ticket_no', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('job_id', models.CharField(blank=True, max_length=20)),
                ('job_no', models.CharField(blank=True, max_length=20)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('pr_date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_crew',
        ),
        migrations.RemoveField(
            model_name='timeclock',
            name='hours_worked',
        ),
         migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(max_length=20, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(max_length=1, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='dept',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='hours_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('ot1', 'Overtime 1')], default='regular', max_length=7),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='job_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='non_bill',
            field=models.CharField(blank=True, choices=[('', 'Blank'), ('y', 'Yes')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='perdiem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='phase',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='project_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_timeclocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='task_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='tkt_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timeclock',
            name='wc_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_crew_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_timeclocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_unique_employee_ids),
    ]
