# Generated by Django 5.1.6 on 2025-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_add_employee_fields_with_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
