# Generated by Django 5.1.6 on 2025-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_employeecertification_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
