# Generated by Django 5.1.6 on 2025-03-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_profile_notes_profile_termination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.site'),
        ),
    ]
