# Generated by Django 5.1.6 on 2025-03-16 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_trainingrecord_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={},
        ),
        migrations.AddField(
            model_name='certification',
            name='is_site_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeecertification',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeecertification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
