# Generated by Django 5.1.6 on 2025-03-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_clear_and_migrate_sites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecertification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobsite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeecertification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='default_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobsite'),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobsite'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobsite'),
        ),
    ]
