# Generated by Django 5.1.6 on 2025-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_hazardreport_is_silenced_suggestion_is_silenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AR', 'Arkansas'), ('FL', 'Florida'), ('LA', 'Louisiana'), ('MS', 'Mississippi'), ('NC', 'North Carolina'), ('OK', 'Oklahoma'), ('TX', 'Texas'), ('OF', 'Offshore')], help_text='State where this crew operates', max_length=2, null=True),
        ),
    ]
